version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    # Run the FastAPI app.
    command: python app.py

  cron:
    build: .
    # Run the cron job that scrapes every 10 minutes.
    command: python cron.py 